### ISSUE TITLE
Preferred Language Error Issue

### ISSUE THREAD

**Issue by michaelbravothomas** [bionomia/bionomia#304] opened 2023-07-23 18:09 UTC
Found a bug when adding Preferred Language (Choose your preferred language) in settings - When I select English the entry returns an error

Error
Sorry, we experienced an error.
![errorPreferredLanguage](https://github.com/bionomia/bionomia/assets/19720676/de2c270d-08a0-4787-b3e3-bf90ecff3d7a)

**Comment by dshorthouse** [comment] 2023-07-23 18:32
That's a new one, thanks for reporting!

**Comment by dshorthouse** [comment] 2023-07-25 03:58
I've been trying to reproduce this, but have failed to sort out where & how this happens. My suspicions is that there might have been a sequence of actions that had not yet completed just prior to having chosen a language. Is this a persistent, repeatable issue?

**Comment by dshorthouse** [comment] 2024-03-13 15:53
Closing because cannot reproduce.

**Closed by dshorthouse** 2024-03-13 15:53 UTC
